if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin
- echo ${TRAVIS_BUILD_NUMBER} > version
- echo ${TRAVIS_COMMIT} >> version
- docker build  --no-cache -t fiware/service.oauth2provider .
- docker push fiware/service.oauth2provider
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    urls:
      secure: gBxRxXBnD/xAuWUTp06vWBISViEO7UKm6X01C+GOzpMTzMVnQwqegmL/ROrFpPGguOJqe4vhTNU5EKaCt3zlJn/EHMGMbPC4bWi1kH0agfZ3B00XBqBdSYtsCWciwRt+8y9oSYcTi/7r2pcOkG5v0J73RTdOXA3ktk9RF0re/KT/jODiv+6XKYeHj+pJVtiQQYKX5iSkZn40o3jdtwOq7zwWI3KswH4nm4fbnFQNv90BfaLQ0IG8OFOrrTBn3iqPiqIgG1GVHrKqoNI11OA7KaU7cwVK4ZSrTQYtmqEIxXskKvfk1wwpoHnGotwv8aL4c1s2myUyxmlOQaE0X/cpUqIEa6x+vVk1p+XDCK6y3lHIu9xiZi6Wxvqm360UgJeopu7VQnHdp6kycCxufrkmTEMlOPd8fTVybeyZcejNgBIFsRllUDBxxSdh00A1lYYLBo2mnvGUcCGnE7MbIcde1W2kpL5CILDG2ANqQaawdVnnGb6YdOc514vcjQ/O3kRf+V3o3vvBvAsDwasX/HYqdN4NHyA/vuEh9uGmJlogZJ9KfPVh9KjFM5bu+1no9z7lVbTCc9iWHj+O7t/zsz1Uj9LM6/yc/RivZd18cgCQ+GKqmlBbFJjc4yCYqIbhN1LCJ3MqFndF0Q13IX0IRDLVRzNTo0Sb9sMA2qADs5wpfTE=
