if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- echo ${TRAVIS_BUILD_NUMBER} > version
- echo ${TRAVIS_COMMIT} >> version
- docker build  --no-cache -t fiware/service.oauth2provider .
- docker push fiware/service.oauth2provider
env:
  global:
  - secure: u4mM8Bbb5QVjFbge/QcaHqHxa1SzOuBHPBiUpGtXGAy9ZVRdH/QJghfYyWPjcq2f7jqzNIecEz6GcVv6uSKtuyQ6KWeWJEsev3LkfcZitTIVhyRtOl5Hb0JjYC/dabpkTL/fpSAuAaWw1kW2QTNwib9aT+HUniVXwDfLv5Iu7CmnvreFwfuzKva8DuT1Wk6khw2JOsDSQC0BAePx5IvgnodMbPmmahQ2QdVe/Zt21tAQBMqrm+wxInEWUw+Fe+yjGkoq+dmc05lQvh0lApC8QF+e+mHYisyRLJG9HRD/rJ5HmQGrwRzj5F+lh4xQNIUd8UnNX4nW23IA16nI6dCYWoYfM6iCJ3fYZqJcq5zMRP8plXtB6GhQwsvne1qmVFmsqXhlcypFbLEnW8KKcBABkBYhFOpMkNQXcbq3EohUo/PF+kQoitkJ/lwfU9euUb9ihNOOX4gAZKc72UfxIEaQVKv0Jk3IxTzDjIo26QCcl1gf1S2LAMl+Qk/ISZTfe1jCdy0bnzObwTFurnHYoFIctSDEv0zViFD+rWy+al3a5isDsNcoO2IHJTWf3qCH4BBFbHsHeOQv2rZrDhD08RZpSgaVLGyh89idYMCQVMfuY1cqaqPE2C9ydlMmXLS0cnN6Mncj/Lo4CbcSvV6sDsuGpxzC7i5Q64dO3qNeODX1YnA=
  - secure: D5wzshXk+V3UX4qL6Zxj2ejpIfIP72JArfYIx+M3o+MoFJmCnQeNXQwxmxL59YtR07n3dz5ianfn6n0qx3p2aL5LUaTazlXq28np7ng9Hn3FB3WWGI4Rhfc5wosUXz6tcQ0GjCCd7WBGyd0wSGGjgY3zJad8Gq7b86xumGxzvmXe0t4usmfp/B3rXIfIex/iLPzCCaKzOiGArMyUPoOiWvLR43W2CbqDUwKAncVM33x2WmvguFT7soI0SrOZ2twVmAPNwV7oa2zxJ5P3ehgcBVxhTj2NxvP9FNyjOcqw2+QNVq7YTBlj99B815k25kZo+jzCzG8gihea8H0XDu3CUNNXLFz/9Gv0U6wqQrlFE3k+OyivwyG75zFq5/bGloLjVL1vG5qu/TKxGh37J6jrXbe3qfhUbU4Ufidnt7B/qFSR5sUK+BxcLd2jGBIXXWKdG0Tul9gOOxFQ3hXMIn385euJpY80rMYMCsyF/QLsb4m6l09arbIyUIokOd4rmgmnldDP8dSAvH6KWOzrnl3eb2rX19niOyCStBlqL7xJLWzrlQC8gUx91R/Tiw8wv1AhTNtc+/4QLZux0/SnbA0g1pmgSrY/q428RuWwad+Nz2O0sbHe0CTifB3aNZws4s2Lhfr09ljJk0DCLdwL7Z/1mm6ITh2yadeUwPure2SOzwo=
notifications:
  webhooks:
    urls:
      secure: eoWrNyfAsCa/e98QG9GJ2DblzXsrsmGuctOC24Subfd6Jcurt0odnTTvY/jvCOQ05tahV2EPFLK5giaST03ZzJ24eWIuRpPdczodu8KT4bZ5COB70NryrHTv3+AERuZXUSOGMG/qLvv2N48FgMG5gvhjATuPTRUrHLn0arojskA/Ywp12PxUoqJhC6KByJnms4VWc968myuusUkhEKe955hQ4SEHI1NzOm/cX5lHjQyCHERxf6OJr48DhIlr6FIb5lJS1xubMlsDLBUQO+vkAp6BcxOecKa5RDz9P4gFNN/o6c/dVvGLBxsWfTvTN/CpHGg02G7f23s/yR/UC4flHJPLOk+zPKhBsm2zoGvLhKeNDu9Wh1S36nRK5rzRVh59iu6UkZpdputR54oI+x+J95QqUkcH6OwDPluRCQZubaZ+CnwgXtESOaM2rBz0QLxnf4swf0GgKHvy4zUtS/WGP/Bw0Ni0pR7tBlpkYSYj1l5XIp7U2K/xMVmgrnATrgKTzwZX1w5p+X7PLKRUMwniBbnNSrSz+O+dlbt9R3N3SuRegpWgh7i3OJx9FqvPuIsSjexmvLSa58erf37SkaFSZZ2qvC7oh0/qJ+XcspUbZjBm87j2NMds5y79mN09Yu67MtX6z5GZ2pmXfxDWxHcdYzU+LNCCGGtdIBwCQThqans=
