version: '3'
services:
  oauth2provider:
    image: fiware/service.oauth2provider:latest
    command:
      - '--keyrock=https://account.fiware.org'
      - '--client_id='
      - '--client_secret='
      - '--redirect_uri=http://localhost/oauth2/callback'
      - '--upstream=http://localhost/'
      - '--cookie_key='
      - '--cookie_lifetime=24'
      - '--salt='

  nginx:
    image: nginx
    ports:
        - 0.0.0.0:80:80
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"

  echo:
    image: caa06d9c/echo
